[package]
name = "koch_line_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.11"
nannou = "0.18.1"
once_cell = "1.8.0"

[profile.dev]
debug = true